### ISSUE TITLE
topのロゴ+画像の部分が重そう

### ISSUE THREAD

**Issue by 8miricd** [yzk-gym/yzk-community-site#51]
430kある。これはめちゃ重い。表示ももたついている。
svgのまま圧縮するか、パーツごとに分割して配置するか、pngとかに変換してしまうかしたほうがよさそう。
pngにしちゃうのが楽で確実じゃないかなー。

**Comment by yuu-342** [comment]
これって今テントのとこだけpngにしてロゴと文字は一旦svgになってるんですけど、pngでいいですよね
topが重いとかっこ悪くて嫌だし。
